### PR TITLE
bump slonik to 28.1.1

### PR DESCRIPTION
**Pull request by sylver**
* fix some vulnerabilities
* update types to be compatible with slonik `28.x`
* force `peerDependencies` to `28.x` since the types renaming is a breaking change

### CODE REVIEW

**Comment by sylver** [comment]
Hi @gajus,

Hope you're well. I suppose you're very busy (or maybe in vacations at this time of the year), but could you have a quick look on this one ?
I think that's an easy and quick win and is mandatory to keep `slonik-utilities` in sync with `slonik`.

I can even propose myself to help you as a maintainer on this repo if you need some helping hand. Let me know.

**Comment by gajus** [comment]
I don't get notifications about PRs/comments on PRs that have failing CI jobs. The only way this can get released is if all PR tests are passing.

**Comment by sylver** [comment]
> The only way this can get released is if all PR tests are passing.

@gajus thanks for getting back to me.

It seems you have issues with your Travis context for some time now (even tests for the last release you did were failing).

Screen Shot 2022-08-02 at 2 32 14 PM

Screen Shot 2022-08-02 at 2 38 20 PM
Screen Shot 2022-08-02 at 2 38 35 PM

This is not related to my PR, tests are running fine locally.
You can have a look, changes are light and pretty straightforward.

**Comment by gajus** [comment]
Looks like Travis introduced a breaking change. Changing `node` to fixed version should fix it.

**Comment by sylver** [comment]
> Looks like Travis introduced a breaking change. 

It's not a breaking change, your `.travis.yml` config was out-of-date : 

* Since you switched the codebase to typescript, you didn't update the travis config to install it (error `tsc: not found`), it seems they don't include it by default in their builds unfortunately
* you didn't update node versions since quite some time (I've taken the liberty to switch from `14` to `lts/*` => easier to maintain without thinking about it)
* since you use `node` as a placeholder version that pulls the last active node install (and that version changes as time goes by), you ended up with an incompatibility between the default runner distribution and the last node build (`18`). A more up-to-date distribution with a recent compatible libc binary was necessary, I forced it with the `dist` flag.

Everything looks good now, if that's ok for you.

**Comment by gajus** [comment]
Perfect. Thank you!

**Pull request merged**
